#!/bin/sh

case "$1" in
start)
    echo "Starting lddmodules"
    modprobe hello
    modprobe faulty
    modprobe scull
    ;;
stop)
    echo "Stopping lddmodules"
    rmmod hello
    rmmod faulty
    rmmod scull
    ;;
*)
    echo "Usage: $0 start/stop"
    exit 1
    ;;
esac
exit 0
